FROM php:fpm

# Update the package repository and install additional packages
RUN yum -y update && yum -y install \
    libzip-devel \
    libpng-devel \
    libjpeg-turbo-devel \
    freetype-devel \
    gcc \
    make \
    autoconf \
    automake \
    libtool \
    nginx \
    supervisor \
    && yum clean all

# Installs the pdo_mysql extension
RUN docker-php-ext-install pdo_mysql

# Installs additional PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd zip opcache

# Removes the default Nginx configuration
RUN rm /etc/nginx/nginx.conf && rm -rf /etc/nginx/conf.d/*

# Redirects the NGINX log (access and error) to stdout and stderr
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

# Adds our specific configuration for NGINX
ADD ./DevOps/support/nginx-php.conf /etc/nginx/conf.d/nginx-php.conf

# Adds configuration for Supervisor utility
ADD ./DevOps/support/supervisor.conf /etc/supervisor.conf

# Copies our PHP application
ADD ./DevOps/web/ /var/www/html/

# Exposes port 80
EXPOSE 80

# Sets the routine to be executed when container is started
CMD ["supervisord", "-c", "/etc/supervisor.conf"]